config/routes.rb
Rails.application.routes.draw do
  resources :maps
  get 'avators/new'
  post 'avators' => 'avators#create'

  devise_for :users, :controllers => {
   :registrations => 'users/registrations',
   omniauth_callbacks: 'users/omniauth_callbacks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :submits do
    resources :likes, only: [:create, :destroy]
  end

  resources :mypages




  get 'tops' => 'tops#index'
  root 'submits#index'

end

app/models/submit.rb
class Submit < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :tags, dependent: :destroy
  # accepts_nested_attributes_for :tags, dependent: :destroy
  # accepts_nested_attributes_for :images, dependent: :destroy
  # accepts_nested_attributes_for :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user, dependent: :destroy
  after_validation :geocode

  def self.search(search) #self.でクラスメソッドとしている
    if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
      Submit.where(['name LIKE ?', "%#{search}%"])
    else
      Submit.all #全て表示。
    end
  end

  private
   def geocode
     uri = URI.escape("https://maps.googleapis.com/maps/api/geocode/json?address="+self.address.gsub(" ", "")+"&key=AIzaSyDoht4ANB4eIveBmly94TbKNv4E6Ll61vw")
     res = HTTP.get(uri).to_s
     response = JSON.parse(res)
     self.latitude = response["results"][0]["geometry"]["location"]["lat"]
     self.longitude = response["results"][0]["geometry"]["location"]["lng"]
   end
end

app/controllers/submits_controller.rb
class SubmitsController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  def index
    @submits = Submit.all

    #ViewのFormで取得したパラメータをモデルに渡す
    @submits = Submit.search(params[:search])
  end

  def new
    @submit = Submit.new
    @submit.tags.build
  end

  def create
    require 'openssl'
    @submit = Submit.new(submit_params)
      #新しいSubmitの保存に成功した場合
    @submit.user_id = current_user.id
    if @submit.save
      if Image.create_images_by(image_params,@submit)

      #index.html.erbにページが移る
        redirect_to action: "index"
      else
        redirect_to action: "new"
      end
      #新しいSubmitの保存に失敗した場合
    else
      #もう一回投稿画面へ
    redirect_to action: "new"
    end
  end

  def show
    @submit = Submit.find(params[:id])
    @like = Like.new
  end

  private
   #セキュリティのため、許可した:name~というデータだけ取ってくるようにする
   def submit_params
    params.require(:submit).permit(:name,:address,:kind,:tag,:impression,:money,:latitude)
   end

   def image_params
     params.require(:submit).permit({image: []})

   end

end

app/helpers/submits_helper.rb
module SubmitsHelper
end

app/views/submits/index.html.erb
<html>
  <head>
    <meta charset="UTF-8">
    <title></title>
  </head>

  <body>
    <script>
// ここからホバーエフェクト
    // ここまでホバーエフェクト
    </script>
  </body>
</html>

<!-- ここからメニューバー -->
<div class="menu">
    <div class="title">MENU</div>
    <ul class="nav">
      <li><%=link_to "Toppage", submits_path %></li>
      <% if user_signed_in? %>
      <li><%=link_to "MyPage", mypages_path %></li>
      <li><%=link_to "Posting", new_submit_path %></li>
      <li><%= link_to 'Avator', edit_mypage_path(current_user) %></li>
      <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
      <%else%>
      <li><%=link_to "SignIn?", user_session_path %></li>
      <%end%>

      <%# ここから検索  %>
      <%= form_tag submits_path,:method => 'get' do %> <%#　projects_pathはモデル名で読みかえること %>
        <p>
          <%= text_field_tag :search, params[:search],:size => '5%'  %>
          <%= submit_tag "Search", :name => nil %>
        </p>
      <% end %>
      <%= yield %>
      <!-- ここまで検索 -->
    </ul>
</div>
<!-- ここまでメニューバー -->

<div class="submits_index">
    <div class="image_box" >
      <% @submits.each_with_index do |t, i|  %>
        <% if i % 3 == 0  %>
          <% if Image.exists?(:submit_id => t.id) %>
            <%= link_to submit_path(t.id) do %>
              <%= image_tag t.images.first.image.to_s ,width: "99%" , :class=>"imageman"%>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="image_box" >
      <% @submits.each_with_index do |t, i|  %>
        <% if i % 3 == 1  %>
          <% if Image.exists?(:submit_id => t.id) %>
            <%= link_to submit_path(t.id) do %>
              <%= image_tag t.images.first.image.to_s ,width: "99%", :class=>"imageman" %>
            <%end%>
          <% end %>
        <% end %>
    <% end %>
    </div>
    <div class="image_box" >
      <% @submits.each_with_index do |t, i|  %>
        <% if i % 3 == 2  %>
          <% if Image.exists?(:submit_id => t.id) %>
            <%= link_to submit_path(t.id) do %>
              <%= image_tag t.images.first.image.to_s ,width: "99%" , :class=>"imageman"%>
            <%end%>
          <% end %>
        <% end %>
      <% end %>
    </div>

  </div>
</div>


<!-- ここからホバーエフェクト -->
　
<!-- ここまでホバーエフェクト -->

app/views/submits/new.html.erb
<!-- ここからメニューバー -->
<div class="menu">
    <div class="title">MENU</div>
    <ul class="nav">
      <li><%=link_to "Toppage", submits_path %></li>
      <% if user_signed_in? %>
      <li><%=link_to "MyPage", mypages_path %></li>
      <li><%=link_to "Posting", new_submit_path %></li>
      <li><%= link_to 'Avator', edit_mypage_path(current_user) %></li>
      <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
      <%end%>
    </ul>
</div>
<!-- ここまでメニューバー -->
<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-6">
    <div class="post_box">
    <%= form_for(@submit, :url => { controller: 'submits',action: 'create'}) do |f| %>
      <div class="field">
          <%= f.label :name, "飲食店の名前" %>
          <%= f.text_field :name, :class =>"form-control" %>
      </div>

      <div class="field">
          <%= f.label :address, "住所" %>
          <%= f.text_field :address , :class =>"form-control" %>
      </div>

      <div class="field">
          <%= f.label :kind, "飲食店の種類(ex:カフェ)" %>
          <%= f.text_field :kind, :class =>"form-control"  %>
      </div>

      <div class="field">
          <%= f.label :impression, "感想" %>
          <%= f.text_field :impression , :class =>"form-control" %>
      </div>


      <div class="field">
          <%= f.label :money, "使った金額" %>
          <%= f.text_field :money , :class =>"form-control" %>
      </div>
      <%# <div class="field"> %>
           <%# <%= f.nested_fields_for :tags do |ff| %>
             <%# <%= ff.label :name, "Tag" %>
             <%# <%= ff.text_field :name , :class =>"form-control" %>
             <%# <%= ff.remove_nested_fields_link %>
           <%# <% end %>
           <%# <%= f.add_nested_fields_link :tags %>
       <%# </div> %>

    <%= f.label :image, "写真" %>
      <%= f.file_field :image, :multiple => true  %>

      <div class="action">
          <%= f.submit "Posting" ,:class => "btn btn-primary" %>
      </div>

    <% end %>
    </div>

  </div>
  <div class="col-sm-3"></div>
</div>

app/views/submits/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-1">
    </div>
    <div class="col-sm-10">
      <!-- ここからメニューバー -->
      <div class="menu">
          <div class="title">MENU</div>
          <ul class="nav">
            <li><%=link_to "Toppage", submits_path %></li>
            <% if user_signed_in? %>
            <li><%=link_to "MyPage", mypages_path %></li>
            <li><%=link_to "Posting", new_submit_path %></li>
            <li><%= link_to 'Avator', edit_mypage_path(current_user) %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
            <%end%>
          </ul>
      </div>
      <!-- ここまでメニューバー -->

<link href='https://fonts.googleapis.com/css?family=Varela' rel='stylesheet' type='text/css'>
<!-- ↑これはテレビ -->
      <h1>Henmise</h1>
      <div class="card">
        <div class="image"><%= image_tag @submit.images.first.image.to_s ,width: "90%"%></div>
        <div class="card-body">
          <h3 class="card-title"><%= @submit.name %></h3>
          ♡Like: <%= @submit.likes.count %><br>
          <%# タグ: <%= @submit.tag %>
          <% if user_signed_in? %>
          <% if current_user.already_liked?(@submit) %>
           <%= button_to 'Likeを取り消す', submit_like_path(@submit), method: :delete %>
          <% else %>
           <%= form_for [@submit, @like] do |f| %>
             <%= f.hidden_field :user_id, :value => current_user.id %>
             <%= f.hidden_field :submit_id, :value => @submit.id %>
             <%= f.submit '♡' %>
           <% end %>
           <% end %>
          <% end %>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item">住所: <%= @submit.address %></li>
          <li class="list-group-item">種類: <%= @submit.kind %></li>
          <li class="list-group-item">使った金額: <%= @submit.money %></li>
          <li class="list-group-item">感想: <%= @submit.impression %></li>
          <li class="list-group-item">
            <div id=map></div>
            <script type="text/javascript">
              function initMap() {

                var test = {lat: <%= @submit.latitude %>, lng: <%= @submit.longitude %>};
                var map = new google.maps.Map(document.getElementById('map'), {
                  zoom: 15,
                  center: test
                });
                var transitLayer = new google.maps.TransitLayer();
                transitLayer.setMap(map);

                var contentString = '住所：<%= @submit.address %>';
                var infowindow = new google.maps.InfoWindow({
                  content: contentString
                });

                var marker = new google.maps.Marker({
                  position:test,
                  map: map,
                  title: contentString
                });

                marker.addListener('click', function() {
                  infowindow.open(map, marker);
                });
              }
            </script>
            <script async defer
              src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyDoht4ANB4eIveBmly94TbKNv4E6Ll61vw&callback=initMap">
            </script>
          </li>
          <%# <li class="list-group-item">いいねしたユーザー %>
          <%# <% @submit.liked_users.each do |user| %>
          <%# </li> %>
          <%# <%= link_to user.name, mypages_path %>
          <%# <% end %>

        </ul>
        <!-- <div class="card-body">
          <a href="#" class="card-link">Card link</a>
          <a href="#" class="card-link">Another link</a>
        </div> -->
      </div>

    </div>
    <div class="col-sm-1">
    </div>
  </div>
</div>